name: chat_bot_package
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.2
  adaptive_theme: ^3.2.1

  equatable: ^2.0.3
  provider: ^6.0.5
  get_it: ^7.2.0
  collection: ^1.17.2
 
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  bloc: ^8.1.1
  http: ^0.13.5
  intl: ^0.18.1
  injectable: ^2.1.0
  flutter_swiper_null_safety: ^1.0.2
  extended_image: ^8.0.1
  flutter_svg: ^2.0.5
  retrofit: ^4.0.3
  dio: ^5.1.1
  dotted_decoration: ^2.0.0
  flutter_adaptive_scaffold: ^0.1.4
  bcrypt: ^1.1.3
  animations: ^2.0.7
  expansion_widget: ^0.0.3
  carousel_slider: ^4.2.1
  diffutil_dart: ^4.0.0
  intl_utils: ^2.8.4
  flutter_isolate: ^2.0.4
  jumping_dot: ^0.0.6
  flutter_spinkit: ^5.2.0
  universal_platform: ^1.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  either_dart: ^1.0.0
  animated_text_kit: ^4.2.3
  speech_to_text: ^6.5.1
  flutter_tts: ^3.8.5
  chat_gpt_sdk: ^3.0.7
  flutter_markdown: ^0.7.4+3
  # youtube_player_flutter: ^8.1.2
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  dart_code_metrics: ^5.7.0
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.5
  retrofit_generator: ^7.0.8
  isar_generator: ^3.0.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_intl:
  enabled: true
  class_name: ChatBotLocalizations  # Tên class mặc định
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
